name: AI Text Summarization with Amazon Bedrock
description: |
  This AMP demonstrates an application which uses Amazon Bedrock Models for LLM inference with a customizable summarization usecase.
author: Cloudera Inc.
specification_version: 1.0
prototype_version: 1.0
date: "2023-09-28"

environment_variables:
  AWS_ACCESS_KEY_ID:
    default: "aws_key"
    description: >-
      AWS Key ID. Check the Amazon Bedrock documentation for information about role access
  AWS_SECRET_ACCESS_KEY:
    default: "aws_secret_key"
    description: >-
      AWS Secret Key
  AWS_DEFAULT_REGION:
    default: "us-west-2"
    description: >-
      AWS region

runtimes:
  - editor: PBJ Workbench
    kernel: Python 3.9
    edition: Standard
    
tasks:
  - type: run_session
    name: Install Dependencies
    script: amp_1_session-install-deps/setup.py
    short_summary: Install Dependencies
    kernel: python3
    cpu: 2
    memory: 4
    
  - type: start_application
    name: CML Text Summarization with Amazon Bedrock
    subdomain: cml-task
    script: amp_2_app/bedrock-app.py
    long_summary: Launching Application and UI. Bedrock model invocation will use the configured AWS role. 
    cpu: 2
    memory: 8
    environment_variables:
      TASK_TYPE: START_APPLICATION
